from yacs.config import CfgNode as CN

MODELS = CN()

MODELS.NAME = "HRNet48v2"
MODELS.DEVICE = "cuda"
MODELS.HEAD_SIZE  = [[2]]
MODELS.OUT_FEATURE_CHANNELS = 256
MODELS.N_CLUSTERS = 5
MODELS.LOSS_WEIGHTS = CN(new_allowed=True)
MODELS.SMOOTH_OFFSET_LABEL = False #check
MODELS.SMOOTH_OFFSET_KERNEL =  3
